# Generated by Django 5.1.3 on 2024-12-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='model name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('image', models.URLField(verbose_name='image')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('lte_exists', models.BooleanField(verbose_name='LTE on board')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
